"""empty message

Revision ID: 213081bdceda
Revises: 12a830c7dcbc
Create Date: 2023-01-03 23:14:44.041542

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '213081bdceda'
down_revision = '12a830c7dcbc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=True))
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
