"""empty message

Revision ID: 2bbd06632c8d
Revises: 196b814e8564
Create Date: 2023-01-05 12:53:16.949460

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2bbd06632c8d'
down_revision = '196b814e8564'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('available_inventory', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('customer_id', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('video_id', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'rental', 'customer', ['customer_id'], ['id'])
    op.create_foreign_key(None, 'rental', 'video', ['video_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_constraint(None, 'rental', type_='foreignkey')
    op.drop_column('rental', 'videos_checked_out_count')
    op.drop_column('rental', 'video_id')
    op.drop_column('rental', 'customer_id')
    op.drop_column('rental', 'available_inventory')
    # ### end Alembic commands ###
