"""empty message

Revision ID: 3eec6082b432
Revises: 545926c08127
Create Date: 2023-01-05 13:46:52.233712

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3eec6082b432'
down_revision = '545926c08127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('avaliable_inventory', sa.Integer(), nullable=True))
    op.add_column('rental', sa.Column('due_date', sa.String(), nullable=True))
    op.add_column('rental', sa.Column('name', sa.String(), nullable=True))
    op.add_column('rental', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'videos_checked_out_count')
    op.drop_column('rental', 'name')
    op.drop_column('rental', 'due_date')
    op.drop_column('rental', 'avaliable_inventory')
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###
