"""Changed phone_number attr to phone for Customer class

Revision ID: 3f7ddb648abb
Revises: d6e919e969dd
Create Date: 2023-01-04 15:33:30.154196

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f7ddb648abb'
down_revision = 'd6e919e969dd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone', sa.String(), nullable=False))
    op.drop_column('customer', 'phone_number')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('phone_number', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('customer', 'phone')
    # ### end Alembic commands ###
