"""add checked_in attribute to Rental with default value

Revision ID: 423c2d11c0ed
Revises: ef871748b608
Create Date: 2023-01-08 12:58:22.837237

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '423c2d11c0ed'
down_revision = 'ef871748b608'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checked_in', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checked_in')
    # ### end Alembic commands ###
