"""empty message

Revision ID: 48784f087bfd
Revises: fd6979ad3349
Create Date: 2023-01-03 20:32:47.601762

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '48784f087bfd'
down_revision = 'fd6979ad3349'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('name', sa.Text(), nullable=True))
    op.add_column('customer', sa.Column('phone_number', sa.Text(), nullable=True))
    op.add_column('customer', sa.Column('register_at', sa.DateTime(), nullable=True))
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out_count')
    op.drop_column('customer', 'register_at')
    op.drop_column('customer', 'phone_number')
    op.drop_column('customer', 'name')
    # ### end Alembic commands ###
