"""empty message

Revision ID: 59597455d088
Revises: ef71346dbe93
Create Date: 2023-01-07 13:25:30.901381

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '59597455d088'
down_revision = 'ef71346dbe93'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out_count')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
