"""empty message

Revision ID: 66b1b8ce0a47
Revises: 7ab575ab9457
Create Date: 2023-01-06 15:41:54.650206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66b1b8ce0a47'
down_revision = '7ab575ab9457'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('available_inventory', sa.Integer(), nullable=True))
    op.drop_column('rental', 'avaliable_inventory')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('avaliable_inventory', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('rental', 'available_inventory')
    # ### end Alembic commands ###
