"""empty message

Revision ID: 7ab575ab9457
Revises: 56ae889deebc
Create Date: 2023-01-05 22:53:17.009269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7ab575ab9457'
down_revision = '56ae889deebc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('is_checked_out', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'is_checked_out')
    # ### end Alembic commands ###
