"""added status to rental and available_inventory to video models.

Revision ID: 7f3a3cc43a5c
Revises: 8b1b64498a3f
Create Date: 2023-01-07 16:24:54.863815

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7f3a3cc43a5c'
down_revision = '8b1b64498a3f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rentals', sa.Column('status', sa.String(), nullable=True))
    op.add_column('video', sa.Column('available_inventory', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('video', 'available_inventory')
    op.drop_column('rentals', 'status')
    # ### end Alembic commands ###
