"""empty message

Revision ID: b5ba421de486
Revises: e21d624c50db
Create Date: 2023-01-07 14:34:31.782467

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b5ba421de486'
down_revision = 'e21d624c50db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('customer', 'videos_checked_out_count')
    op.add_column('rental', sa.Column('due_date', sa.DateTime(), nullable=True))
    op.drop_column('rental', 'is_checked_out')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('is_checked_out', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_column('rental', 'due_date')
    op.add_column('customer', sa.Column('videos_checked_out_count', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
