"""add checkout_date attribute to Rental table

Revision ID: f81108b287d9
Revises: 423c2d11c0ed
Create Date: 2023-01-08 13:51:02.782689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f81108b287d9'
down_revision = '423c2d11c0ed'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('rental', sa.Column('checkout_date', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('rental', 'checkout_date')
    # ### end Alembic commands ###
